### ISSUE TITLE
Override flag is not saved for custom values

### ISSUE THREAD

**Issue by michael-e** [brendo/default_event_values#2]
The override flag will not be saved to the event file, so it will be lost upon saving:

```
"MICHAEL_SAYS" => array(
    'value' => 'hello',
    'override' => 'no',
    'custom' => 'yes'
),
```

**Comment by michael-e** [comment]
There is an offset in the POST (override) array. If you change line 106 ff. from:

```
$default_values .= $this->addCustomDefaultValue(array(
    'field' => $dv['key'][$i],
    'value' => $dv['value'][$i],
    'override' => $dv['override'][$i]
));
```

to:

```
$default_values .= $this->addCustomDefaultValue(array(
    'field' => $dv['key'][$i],
    'value' => $dv['value'][$i],
    'override' => $dv['override'][$i+1]
));
```

it works. But that is not super-elegant...

**Comment by brendo** [comment]
Yeah it's a tricky issue to solve. I'm going to have a look through some other duplicator code and see what they do in this sort of situation.

I had thought of the `$i+1`, but I felt the same way
