### ISSUE TITLE
Override does not work for custom values

### ISSUE THREAD

**Issue by michael-e** [brendo/default_event_values#4]
This is probably related to line 164:

```
// @todo Support override
```

:-)

**Comment by michael-e** [comment]
Sorry, it turns out that it works for standard (hidden) fields if I edit the datasource manually. (Related to issue #3).

**Comment by brendo** [comment]
Do you mean #2? And yes it's on today's todo list to make this work for array data.

**Comment by michael-e** [comment]
Yes, #2. And I meant the event file, not the DS file. I should have some sleep...

**Comment by brendo** [comment]
Go sleep, when you wake up you'll have shiny new toys that work to play with (and I'll look into that Symphony bug RE: Upload field)

**Comment by michael-e** [comment]
Thanks, Brendo!

**Comment by brendo** [comment]
Almost there on this, just need to get it working correctly with deeply nested arrays
