### ISSUE TITLE
MAX_FILE_SIZE custom value does not work

### ISSUE THREAD

**Issue by michael-e** [brendo/default_event_values#5]
I can't figure out why a `MAX_FILE_SIZE` value has no effect. I thought it _should_ work because the extension uses the `EventPreSaveFilter` delegate. I even dumped out the `$_POST` array, and everything looks good at this point. But no error is triggered if the file size exceeds the setting. (It works fine, however, when I apply the setting directly to my form as a hidden field.)

**Comment by michael-e** [comment]
It probably boils down to this: This value can not be manipulated in Symphony because this is a native PHP thing. Either this field is posted as a hidden value (so PHP "sees it coming", preceding the file input field) or it won't work.

**Comment by brendo** [comment]
I'll see if there's anything that can be done about this.

**Comment by brendo** [comment]
Spoke to @rowan-lewis about this quickly and it looks like your correct and it can't be done.

Would still like to have a read around to be 100% sure.

**Comment by brendo** [comment]
You are 100% right, it can't be set from the server side.
